### PR TITLE
Remove unused apigroups

### PR DESCRIPTION
**Pull request by VaishnaviHire**
This commit removes unused apigroups, since these resources are
not used by RHODS and return errors for ocp 4.8 due to backward
incompatibility of the corresponding apis.

- [x] The commits are squashed in a cohesive manner and have meaningful messages.
- [x] For commits that came from upstream, `[UPSTREAM]` has been prepended to the commit message
- [x] JIRA link(s): https://issues.redhat.com/browse/RHODS-2301
- [x] The Jira story is acked
- [x] An entry has been added to the latest build document in [Build Announcements Folder](https://drive.google.com/drive/folders/1sgkK1WZgGo9CXsLizNe0GbAzVKuSKrZL).
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious)

### CODE REVIEW

**Comment by anishasthana** [comment]
@VaishnaviHire could you update the build doc and stuff?

**Review by crobby — COMMENTED** [review]
Testing this now

**Review by crobby — APPROVED** [review]
I've tested this.  It works. /lgtm

**Pull request merged**
