### PR TITLE
Remove odh-manifests git submodule

### PR DESCRIPTION
**Pull request by samuelvl**
## Description
Remove odh-manifests git submodule dependency.

### CODE REVIEW

**Review by anishasthana — APPROVED** [review]
/lgtm

**Comment by VaishnaviHire** [comment]
I think we need to update CI tests before merging this ?
```
Storing signatures
error: error copying source path /go/src/github.com/red-hat-data-services/opendatahub-operator/odh-manifests/tests/. to .: exit status 1
```

**Comment by LaVLaS** [comment]
@samuelvl I assume this is aligned with changes in the cpaas & livebuilder for the rhods 1.19 builds?

**Comment by samuelvl** [comment]
@LaVLaS Correct

**Comment by LaVLaS** [comment]
@samuelvl Can you rebase this PR and we will merge it in

**Review by LaVLaS — APPROVED** [review]
/lgtm

**Pull request merged**
