### PR TITLE
Remove Postgres instance Deletion

### PR DESCRIPTION
**Pull request by VaishnaviHire**
## Merge criteria:

- [x] The commits are squashed in a cohesive manner and have meaningful messages.
- [ ] For commits that came from upstream, `[UPSTREAM]` has been prepended to the commit message.
- [x] JIRA link(s): Jira Issue: https://issues.redhat.com/browse/RHODS-4906
- [x] The Jira story is acked.
- [x] Live build image:  quay.io/modh/rhods-operator-live-catalog:1.16.0-rhods-4906
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Review by anishasthana — COMMENTED** [review]
/lgtm

Changes overall look good (the dependency updates are actually confusing me, to be honest).

**Comment by VaishnaviHire** [comment]
Testing Instructions:
- Deploy live build quay.io/modh/rhods-operator-live-catalog:1.16.0-rhods-4906
- Trigger Addon Uninstall on OSD. Verify KFDef deletion is not blocked by Postgres

**Comment by VaishnaviHire** [comment]
@tarukumar This change is also included in the live-build provided in [this PR](https://github.com/red-hat-data-services/odh-deployer/pull/257).

**Review by LaVLaS — COMMENTED** [review]
/lgtm

Waiting on a test run but the changes look clean

**Review by LaVLaS — APPROVED** [review]
/approve

Deployed this on AWS and the install was successful and the uninstall was even better

**Comment by LaVLaS** [comment]
Rhods livebuild for these changes with KFNBC and migration script: [quay.io/llasmith/rhods-operator-live-catalog:1.16.0-dashboard-kfnbc](https://quay.io/llasmith/rhods-operator-live-catalog:1.16.0-dashboard-kfnbc)

**Pull request merged**
