### PR TITLE
Pull fix for JH CI test failure due JUPYTERHUB_DEFAULT_GROUP_DENIED

### PR DESCRIPTION
**Pull request by LaVLaS**
No Jira story since this is fix to resolve openshift-ci test failures with no change to operator code or manifest deployments

Signed-off-by: Landon LaSmith <LLaSmith@redhat.com>

- [ ] The commits are squashed in a cohesive manner and have meaningful messages.
- [ ] For commits that came from upstream, `[UPSTREAM]` has been prepended to the commit message
- [ ] JIRA link(s): N/A
- [ ] The Jira story is acked
- [ ] An entry has been added to the latest build document in [Build Announcements Folder](https://drive.google.com/drive/folders/1sgkK1WZgGo9CXsLizNe0GbAzVKuSKrZL).
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious)

### CODE REVIEW

**Comment by crobby** [comment]
/test all
seems frozen

**Comment by crobby** [comment]
@LaVLaS This might also need the centos:8 -> stream change.

**Comment by crobby** [comment]
@LaVLaS I think I see what might be going on here...
The change needs to first get merged to rhds/odh-manifests, then we'd pull that change here as an update of the odh-manifests submodule.  I'm pretty sure that's what's making the image builds go crazy.

**Comment by LaVLaS** [comment]
> @LaVLaS I think I see what might be going on here... The change needs to first get merged to rhds/odh-manifests, then we'd pull that change here as an update of the odh-manifests submodule. I'm pretty sure that's what's making the image builds go crazy.

That makes sense due to the `odh-manifests` submodule referencing `origin/pull/201/head` commit

**Review by crobby — APPROVED** [review]
/lgtm

**Pull request merged**
