### PR TITLE
Update go.sum to work with go-toolset

### PR DESCRIPTION
**Pull request by VaishnaviHire**
## Merge criteria:

- [ ] The commits are squashed in a cohesive manner and have meaningful messages.
- [ ] For commits that came from upstream, `[UPSTREAM]` has been prepended to the commit message.
- [ ] JIRA link(s):
- [ ] The Jira story is acked.
- [ ] Live build image: 
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Review by zdtsw — APPROVED** [review]
/lgtm

**Comment by zdtsw** [comment]
@anishasthana or @LaVLaS can you approve this?

**Comment by anishasthana** [comment]
What is this change doing exactly?

**Review by ykaliuta — APPROVED** [review]

**Review by anishasthana — APPROVED** [review]
Approving/merging as enough platform members have approved the PR

**Comment by VaishnaviHire** [comment]
> Approving/merging as enough platform members have approved the PR

v1 modules are outdated. Image build fails when updated to go-toolset 1.19

Ref Jira: https://issues.redhat.com/browse/RHODS-12559

This PR just updates go.sum by doing
```
go mod tidy
```

**Pull request merged**
