### PR TITLE
[UPSTREAM] Update manifests for RHODS-4820

### PR DESCRIPTION
**Pull request by VaishnaviHire**
- [x] The commits are squashed in a cohesive manner and have meaningful messages.
- [x] For commits that came from upstream, `[UPSTREAM]` has been prepended to the commit message.
- [x] JIRA link(s): https://issues.redhat.com/browse/RHODS-4820
- [x] The Jira story is acked.
- [x] Live build image: quay.io/modh/rhods-operator-live-catalog:1.15.0-rhods-4820
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Comment by VaishnaviHire** [comment]
/hold 

till `odh-manifests` PR is merged

**Review by lugi0 — APPROVED** [review]

**Review by anishasthana — CHANGES_REQUESTED** [review]
@VaishnaviHire this PR has a merge conflict.

**Review by anishasthana — APPROVED** [review]
/lgtm

**Review by LaVLaS — APPROVED** [review]
/lgtm

**Pull request merged**
